apiVersion: v1
kind: Secret
metadata:
  name: caf-accounts-master
type: Opaque
data:
  DB_VENDOR: TVNTUUw=
  DB_ADDR: NTIuMTQ5LjI1NC40Mg
  DB_DATABASE: Rk9OVElDX0dPVkNPVF9BQ0NPVU5UUwo=
  DB_USER: Z292Y290Cg==
  DB_PASSWORD: QUU2ZXJDQU9TOW4K
  KEYCLOAK_USER: Z292Y290YWRtaW4K
  KEYCLOAK_PASSWORD: WjI5MlkyOTBZV1J0YVc0PQ==